spring.application.name=blogapp

spring.datasource.url=jdbc:postgresql://dpg-d8no6dkm0tmc73eb38l0-a:5432/blogdb_schv
spring.datasource.username=blogdb_schv_user
spring.datasource.password=WtGsXjWzPesI0vTUaM1J1M12mZf7qwxG


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jps.properties.hibernate.format_sql=true